<?php

return [
    [
        'pattern' => '/marketplace-customer/helloWorld',
        'method' => 'GET',
        'namespace' => 'A7Pro\Marketplace\Customer\Presentation\Controllers',
        'controller' => 'hello',
        'action' => 'getHello',
    ],
    [
        'pattern' => '/marketplace-customer/getProductRecommendation',
        'method' => 'GET',
        'namespace' => 'A7Pro\Marketplace\Customer\Presentation\Controllers',
        'controller' => 'product',
        'action' => 'getProductRecommendation',
    ],
    [
        'pattern' => '/marketplace-customer/searchProduct',
        'method' => 'GET',
        'namespace' => 'A7Pro\Marketplace\Customer\Presentation\Controllers',
        'controller' => 'product',
        'action' => 'searchProduct',
    ],
    [
        'pattern' => '/marketplace-customer/getProductDetail/{productId}',
        'method' => 'GET',
        'namespace' => 'A7Pro\Marketplace\Customer\Presentation\Controllers',
        'controller' => 'product',
        'action' => 'getProductDetail',
    ],
    [
        'pattern' => '/marketplace-customer/cart/add',
        'method' => 'POST',
        'namespace' => 'A7Pro\Marketplace\Customer\Presentation\Controllers',
        'controller' => 'cart',
        'action' => 'add',
    ],
    [
        'pattern' => '/marketplace-customer/cart/setQty',
        'method' => 'POST',
        'namespace' => 'A7Pro\Marketplace\Customer\Presentation\Controllers',
        'controller' => 'cart',
        'action' => 'setQty',
    ],
    [
        'pattern' => '/marketplace-customer/cart/delete/{cart_id}',
        'method' => 'POST',
        'namespace' => 'A7Pro\Marketplace\Customer\Presentation\Controllers',
        'controller' => 'cart',
        'action' => 'delete',
    ],
    [
        'pattern' => '/marketplace-customer/cart/get',
        'method' => 'POST',
        'namespace' => 'A7Pro\Marketplace\Customer\Presentation\Controllers',
        'controller' => 'cart',
        'action' => 'get',
    ],
    [
        'pattern' => '/marketplace-customer/review/write/{order_id}',
        'method' => 'POST',
        'namespace' => 'A7Pro\Marketplace\Customer\Presentation\Controllers',
        'controller' => 'review',
        'action' => 'write',
    ],
    [
        'pattern' => '/marketplace-customer/review/reply',
        'method' => 'POST',
        'namespace' => 'A7Pro\Marketplace\Customer\Presentation\Controllers',
        'controller' => 'review',
        'action' => 'reply',
    ],
    [
        'pattern' => '/marketplace-customer/review/get',
        'method' => 'GET',
        'namespace' => 'A7Pro\Marketplace\Customer\Presentation\Controllers',
        'controller' => 'review',
        'action' => 'get',
    ],
    [
        'pattern' => '/marketplace-customer/getProfile',
        'method' => 'POST',
        'namespace' => 'A7Pro\Marketplace\Customer\Presentation\Controllers',
        'controller' => 'profile',
        'action' => 'getProfile',
    ],
    [
        'pattern' => '/marketplace-customer/addAddress',
        'method' => 'POST',
        'namespace' => 'A7Pro\Marketplace\Customer\Presentation\Controllers',
        'controller' => 'profile',
        'action' => 'addAddress',
    ],
    [
        'pattern' => '/marketplace-customer/getAddress',
        'method' => 'POST',
        'namespace' => 'A7Pro\Marketplace\Customer\Presentation\Controllers',
        'controller' => 'profile',
        'action' => 'getAddress',
    ],
    [
        'pattern' => '/marketplace-customer/order',
        'method' => 'POST',
        'namespace' => 'A7Pro\Marketplace\Customer\Presentation\Controllers',
        'controller' => 'order',
        'action' => 'order',
    ],
    [
        'pattern' => '/marketplace-customer/orders',
        'method' => 'GET',
        'namespace' => 'A7Pro\Marketplace\Customer\Presentation\Controllers',
        'controller' => 'order',
        'action' => 'showOrders',
    ],
    [
        'pattern' => '/marketplace-customer/order/get',
        'method' => 'GET',
        'namespace' => 'A7Pro\Marketplace\Customer\Presentation\Controllers',
        'controller' => 'order',
        'action' => 'get',
    ],
    [
        'pattern' => '/marketplace-customer/order/setDone',
        'method' => 'POST',
        'namespace' => 'A7Pro\Marketplace\Customer\Presentation\Controllers',
        'controller' => 'order',
        'action' => 'setDone',
    ],
    [
        'pattern' => '/marketplace-customer/order/cancel/{order_id}',
        'method' => 'POST',
        'namespace' => 'A7Pro\Marketplace\Customer\Presentation\Controllers',
        'controller' => 'order',
        'action' => 'cancel',
    ],
    [
        'pattern' => '/marketplace-customer/invoice/get',
        'method' => 'GET',
        'namespace' => 'A7Pro\Marketplace\Customer\Presentation\Controllers',
        'controller' => 'invoice',
        'action' => 'get',
    ],
    [
        'pattern' => '/marketplace-customer/cart/update/catatanKePenjual',
        'method' => 'POST',
        'namespace' => 'A7Pro\Marketplace\Customer\Presentation\Controllers',
        'controller' => 'cart',
        'action' => 'addCatatanKePenjual',
    ],
];
